# Stage 1のコンテナ
FROM golang:1.25-alpine AS builder

ENV GOPATH=

RUN mkdir /app
WORKDIR /app

COPY ./ ./

RUN go build -o /main ./main.go

# Stage 2のコンテナ
FROM alpine:3.22

RUN apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

ENV TZ='Asia/Tokyo'
ENV LANG='ja_JP.UTF-8'
EXPOSE 8080

COPY --from=builder /main .
ENTRYPOINT ["./main"]
